# Generated by Django 4.2.7 on 2023-11-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
